version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysecretpassword
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
